#' @title Variable importance plot
#'
#' @description
#'
#' Variable importance, as measured in the proportion of total branches used for a given variable. Error bars show standard deviation across iterations.
#'
#' Variables that are explicitly dropped in the model are included as "0" in the variable importance table, but not plotted; variables that are included but used zero times are shown in both.
#'
#' @param model The dbarts model object
#' @param plots Turn this on for a nice variable contribution plot
#' @param agg.cats Logical (default TRUE), whether or not to aggregate the contributions of the binary variables generated by one-hot encoding of the factor levels of each categorical variable, by summing up their proportions of branches used.
#'
#'
#' @export
#'
#'

varimp <- function(model, plots=FALSE, agg.cats=TRUE) {

  if(!("fit" %in% names(model))) {
    stop("Please add \", keeptrees=TRUE\" to your dbarts model call")
  }
  if(class(model)=='rbart') {
    # basenames <- unlist(attr(model$fit[[1]]$data@x,"drop"))
    # names <- names(which(basenames==FALSE))
    # the above would also drop categorical variables; replaced below
    varimps <- rowMeans(model$varcount/colSums(model$varcount))
    basenames <- unlist(attr(model$fit[[1]]$data@x, "term.labels"))
    names <- names(varimps)
    fitobj <- model$fit[[1]]
  }
  if(class(model)=='bart') {
    # basenames <- unlist(attr(model$fit$data@x,"drop"))
    # names <- names(which(basenames==FALSE))
    # the above would also drop categorical variables; replaced below
    varimps <- colMeans(model$varcount/rowSums(model$varcount))
    basenames <- unlist(attr(model$fit$data@x, "term.labels"))
    names <- names(varimps)
    fitobj <- model$fit
  }

  # missing <- attr(fitobj$data@x,"term.labels")[!(attr(fitobj$data@x,"term.labels") %in%
  #                                                   names(unlist(attr(fitobj$data@x,"drop"))))]
  # the above would cause error with categorical variables; replaced with:
  missing <- basenames[(basenames %in% names(which(unlist(attr(fitobj$data@x, "drop")) == 1)))]

  if(length(missing)>0) {
    message("dbarts auto-dropped this variable(s). You will probably want to remove it")
    message(paste(missing,collapse = ' '), ' \n')
  }


  # NEW BLOCK (TO AGGREGATE CATEGORICAL VARIABLES):
  if (agg.cats) {
    cat.vars <- names(which(lapply(attr(fitobj$data@x, "drop"), length) > 1))
    names.nosuffix <- names
    for (v in cat.vars) {
      v.inds <- grep(v, colnames(fitobj$data@x))
      names.nosuffix[v.inds] <- v
    }
    varimps.df <- data.frame(names = names, basenames = names.nosuffix, varimps, row.names = NULL)
    var.df <- aggregate(varimps.df$varimps, by = list(varimps.df$basenames), FUN = sum)
    names(var.df) <- c("names", "varimps")
    var.df <- var.df[order(var.df$varimps, decreasing = TRUE), ]

  } else {  # if !agg.cats
    var.df <- data.frame(names, varimps, row.names = NULL)
  }

  if(length(missing)>0) {
    missing.df <- data.frame(names = missing, varimps = 0)
    var.df <- rbind(var.df, missing.df)
  }

  var.df$names <- factor(var.df$names)
  var.df <- transform(var.df, names = reorder(names,
                                              -varimps))

  if(plots==TRUE){
    #g1 <- ggplot2::ggplot(var.df, aes(y=varimps, x=names)) +
    #  geom_bar(stat="identity", color="black") +
    #  theme(axis.text.x = element_text(angle = 45)) +
    #  ylab("Relative importance") + theme_bluewhite()
    #print(g1)

    if(class(model)=='rbart') {
      rel <- t(model$varcount/colSums(model$varcount))
    } else {
      rel <- model$varcount/rowSums(model$varcount)
    }
    colnames(rel) <- names

    # NEW BLOCK (TO AGGREGATE CATEGORICAL VARIABLES)
    if (agg.cats) {
      rel.agg <- apply(rel, 1, aggregate, sum, by = list(names.nosuffix))
      rel.agg.names <- rel.agg[[1]][, "names"]
      rel.agg <- lapply(rel.agg, getElement, "x")
      rel <- do.call(rbind.data.frame, rel.agg)
      colnames(rel) <- rel.agg.names
    }

    rel %>% data.frame() %>% gather() %>%
      group_by(key) %>%
      summarise(mean = mean(value),
                sd = sd(value, na.rm = TRUE)) %>%
      transform(Var = reorder(key, mean)) %>%
      ggplot(aes(x = Var, y = mean)) +
      geom_pointrange(aes(y = mean, x = Var, ymin = mean-sd, ymax = mean+sd),
                      color="#00AFDD") +
      xlab(NULL) + ylab("Variable importance") + coord_flip() +
      theme_bw() + theme(legend.position = "none",
                         axis.title.x = element_text(size=rel(1.3), vjust = -0.8),
                         axis.text.y = element_text(size=rel(1.4)),
                         plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
                         panel.grid.minor = element_blank(),
                         panel.grid.major.x = element_line(color='grey',
                                                           linetype='dashed')) -> p

    print(p)

  }

  return(var.df)

}

